version: "3"

services:
  application_login:
    build: .
    command: npm start
    ports:
      - "3002:3000"
    volumes:
      - .:/usr/app
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:3.0.4
    ports:
      - "27017:27017"
    volumes:
      - './data:/data/db'

networks:
  backend_login:
    driver: bridge